### ISSUE TITLE
Configuration header link only refers to Config-db

### ISSUE THREAD

**Issue by paddatrapper** [flanksource/docs#25]
To me, the Configuration link in the header would refer to how to configure Incident Commander, instead it only talks about Config-db and links to https://docs.flanksource.com/config-db/tutorials/install-helm/

**Comment by paddatrapper** [comment]
Maybe it should be renamed to Config-db or Data Configuration

**Comment by adityathebe** [comment]
We decided that we'll go with "Configuration Management"
